### ISSUE TITLE
view_log error:can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by WangLanxiao** [wkentaro/pytorch-fcn#100]
When I follow the voc examples, I got problems of visualizing the logs in command
./view_log logs/XXX/log.csv
with error

can't multiply sequence by non-int of type 'float'

**Comment by AbnerCSZ** [comment]
I met the same problem. Did you solve it?

**Comment by WangLanxiao** [comment]
> I met the same problem. Did you solve it?

I still can't solve it.

**Comment by wkentaro** [comment]
Sometimes the loss can be inf or nan. Maybe that's the reason why you have this error.

**Comment by AbnerCSZ** [comment]
> Sometimes the loss can be inf or nan. Maybe that's the reason why you have this error.

I agree with you. And I find nan in log.csv. Could you tell me how can I solve it?

**Comment by wkentaro** [comment]
I reproduced this error on my env with Python3.
https://github.com/wkentaro/pytorch-fcn/pull/102 fixes this error.

**Comment by AbnerCSZ** [comment]
66666
