### ISSUE TITLE
data can not be downloaded by download_dataset.sh?

### ISSUE THREAD

**Issue by sunjinr** [wkentaro/pytorch-fcn#103]
when I run `train_fcn32s.py -g 0` it says `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\****/data/datasets\\VOC/benchmark_RELEASE/dataset\\train.txt'`, is it because data can not be downloaded by download_dataset.sh? then how to handle it? thx.

**Comment by wkentaro** [comment]
Maybe this is the / or \ problem for the path. 
You need to replace all / to \ if you would like to use it on Windows.
