### ISSUE TITLE
support python 2.7 or 3.x ? 

### ISSUE THREAD

**Issue by zzpzym** [wkentaro/pytorch-fcn#105]
Could you write which python supported in `README.md` please.
Thanks

**Comment by wkentaro** [comment]
As noted by the badge, both Python versions are supported. 

![0bc67590-d682-4cf1-9e46-4513aba9760a](https://user-images.githubusercontent.com/4310419/53320128-eeac4400-38d4-11e9-9cb3-573e312014e6.jpeg)
