### ISSUE TITLE
Training `FCN32s` and using that model to train `FCN16s`

### ISSUE THREAD

**Issue by bhashithe** [wkentaro/pytorch-fcn#107]
I have a very small dataset and i want to use transfer learning in a particular training mechanism in which I am going to train FCN32s on some extracted images and then use that weights as a pretrained model to train FCN16s. I see you have done the same thing in your examples.

I am using your train_fcn16s.py and train_fcn32s.py files in the examples. and providing the model_best.pth.tar file as pretrained-model but when i do that, i get an exception like this

``` python
  File "train_fcn16s.py", line 91, in main                                                                                                                            
    fcn32s.load_state_dict(state_dict)                                                                                                                                
  File "/home/bhashithe/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict 
    self.__class__.__name__, "\n\t".join(error_msgs))) 
RuntimeError: Error(s) in loading state_dict for FCN32s: 
        Missing key(s) in state_dict: "conv1_1.weight", "conv1_1.bias", "conv1_2.weight", "conv1_2.bias", "conv2_1.weight", "conv2_1.bias", "conv2_2.weight", "conv2_2
.bias", "conv3_1.weight", "conv3_1.bias", "conv3_2.weight", "conv3_2.bias", "conv3_3.weight", "conv3_3.bias", "conv4_1.weight", "conv4_1.bias", "conv4_2.weight", "con
v4_2.bias", "conv4_3.weight", "conv4_3.bias", "conv5_1.weight", "conv5_1.bias", "conv5_2.weight", "conv5_2.bias", "conv5_3.weight", "conv5_3.bias", "fc6.weight", "fc6
.bias", "fc7.weight", "fc7.bias", "score_fr.weight", "score_fr.bias", "upscore.weight". 
        Unexpected key(s) in state_dict: "epoch", "iteration", "arch", "optim_state_dict", "model_state_dict", "best_mean_iu".  
During handling of the above exception, another exception occurred:  
```

**Comment by wkentaro** [comment]
I think you should do things like this:

https://github.com/wkentaro/pytorch-fcn/blob/97189cbccb2c9b8bd776b356a1fd4b6c03f67d79/examples/voc/evaluate.py#L50-L53

**Comment by bhashithe** [comment]
I was able to solve it, i was copying the state dict into an object of FCN32, which was initialized with the default value of n_class which is 21. Which is what made up the whole mess.

Changing that to the correct number of classes solved the problem.

Thanks @wkentaro
