### ISSUE TITLE
Hi,I have a question about this line?

### ISSUE THREAD

**Issue by BCWang93** [wkentaro/pytorch-fcn#118]
https://github.com/wkentaro/pytorch-fcn/blob/97189cbccb2c9b8bd776b356a1fd4b6c03f67d79/torchfcn/trainer.py#L195
the len(data) is 1?or it is other number?why you use loss/=len(data) in there?Thanks!

**Comment by wkentaro** [comment]
> the len(data) is 1

yes

> why you use loss/=len(data) in there

because it is proposed in the paper.
