### ISSUE TITLE
question:can i use my own date to train?

### ISSUE THREAD

**Issue by zhengkai17** [wkentaro/pytorch-fcn#126]

**Comment by nankingV** [comment]
i got the same question

**Comment by wkentaro** [comment]
If you implement a dataset class similar to this,
https://github.com/wkentaro/pytorch-fcn/blob/eecae876130930d1261b1ae0113787ddf798abcd/torchfcn/datasets/voc.py#L61-L78

you can just replace the VOC dataset class with your own dataset class:
https://github.com/wkentaro/pytorch-fcn/blob/eecae876130930d1261b1ae0113787ddf798abcd/examples/voc/train_fcn32s.py#L97-L103
