### ISSUE TITLE
How to train my own dataset?

### ISSUE THREAD

**Issue by QbaixueQ** [wkentaro/pytorch-fcn#133]
Thank you for this repo. I tried to train with labelme-labeled pictures and I got an error: 
[Errno 2] No such file or directory: '/home/cuda/data/datasets/VOC/benchmark_RELEASE/dataset/cls/000009.mat'
How should I modify the code so that it can train .png images?

Thanks

**Comment by wkentaro** [comment]
See https://github.com/wkentaro/pytorch-fcn/issues/126
