### ISSUE TITLE
Question about "untransform" method in "VOCClassSegBase" class

### ISSUE THREAD

**Issue by BarryBA** [wkentaro/pytorch-fcn#134]
Thanks for your sharing repo. I have a question about the "untransform" method in "VOCClassSegBase" class of voc.py.
Why we need do the following operations to the image in the untransform?
        img = img.transpose(1, 2, 0)
        img += self.mean_bgr
Hope for your answers. Thanks!

**Comment by wkentaro** [comment]
This is the inverse operation of `self.transform` and used to transform RGB image back to original pixel range (0 - 255).

**Comment by BarryBA** [comment]
> This is the inverse operation of `self.transform` and used to transform RGB image back to original pixel range (0 - 255).

thanks a lot
