### ISSUE TITLE
The weight in deconv doesn`t update?

### ISSUE THREAD

**Issue by Lucksong** [wkentaro/pytorch-fcn#140]
In get_paramers():
def get_parameters(model, bias=False):
    import torch.nn as nn
    modules_skipped = (
        nn.ReLU,
        nn.MaxPool2d,
        nn.Dropout2d,
        nn.Sequential,
        torchfcn.models.FCN32s,
        torchfcn.models.FCN16s,
        torchfcn.models.FCN8s,
    )
    for m in model.modules():
        if isinstance(m, nn.Conv2d):
            if bias:
                yield m.bias
            else:
                yield m.weight
        elif isinstance(m, nn.ConvTranspose2d):
            

# weight is frozen because it is just a bilinear upsampling

            if bias:
                assert m.bias is None
        elif isinstance(m, modules_skipped):
            continue
        else:
            raise ValueError('Unexpected module: %s' % str(m))

**Comment by wkentaro** [comment]
Yeah, it's frozen.

**Comment by Lucksong** [comment]
But why？

**Comment by wkentaro** [comment]
According to the authors, they said it didn't change the final result very much. That was probably because deconvolution layers are difficult to train in general (compared to standard convolutional layer).
