### ISSUE TITLE
FCN8s

### ISSUE THREAD

**Issue by DonghyunK** [wkentaro/pytorch-fcn#15]
Hi,

May I ask that when you update FCN8s or FCN 16s?

Thanks!

**Comment by wkentaro** [comment]
Currently, I'm working on my personal projects, so maybe when I have time for that or I need it.
Chainer implementation is [here](https://github.com/wkentaro/fcn) and it serves FCN16s and FCN8s as well.

**Comment by DonghyunK** [comment]
Thank you for your help!

If I implement those by myself, is it enough to make fcn8s and fcn16s model (fcn8s.py)?

Or is there other thing need to be changed?

Thanks!

**Comment by wkentaro** [comment]
> Or is there other thing need to be changed?

For training, FCN16s needs pre-trained FCN32s, and FCN8s needs both others, so you need to write some weight copying code in training script.

**Comment by volzkzg** [comment]
I'm wondering why we need pre-trained FCN32s for FCN16s and both pretrained FCN32s and FCN16s for FCN8s.
