### ISSUE TITLE
Running custom datasets

### ISSUE THREAD

**Issue by fredpeertje** [wkentaro/pytorch-fcn#152]
I'm trying to train the fcn8s model on a dataset but get the following runtime error:

RuntimeError: shape '[1, 573, 447, 1]' is invalid for input of size 768393

Solution: I used mask images with the RGB format. Converted it to grayscale with range [0,11] (12 classes)

**Comment by peacemo** [comment]
Hi, I come across this problem on CamVid dataset. Would you please be more specific about how to solve this problem. Thank you.

**Comment by YCakira** [comment]
这是来自QQ邮箱的自动回复邮件。嗨，这里是吴颖的信箱。谢谢你的来信，我将会尽快给你回复。
