### ISSUE TITLE
I can't run the train_fcn32s.

### ISSUE THREAD

**Issue by rgd66** [wkentaro/pytorch-fcn#153]
The problem is this:
subprocess.CalledProcessError: Command '['git', 'log', '-n', '1', '--pretty=%h']' returned non-zero exit status 128.
Anyone can help me ?

**Comment by Yuanggyy** [comment]
you can try to git clone https://github.com/wkentaro/pytorch-fcn.git

**Comment by wangfusheng-cqu** [comment]
Did you solve the problem,I meet the same problrm.

**Comment by wkentaro** [comment]
Below should work

```bash
git clone https://github.com/wkentaro/pytorch-fcn.git
cd pytorch-fcn
pip install .

cd examples
./train_fcn32s.py
```
