### ISSUE TITLE
Final layer deconvolutional filters are not fixed

### ISSUE THREAD

**Issue by JJ-res101** [wkentaro/pytorch-fcn#155]
In paper, Final layer deconvolutional filters are fixed to bilinear inertpolation. But I found this implement don't do that.Is that right?

**Comment by wkentaro** [comment]
It's frozen here
https://github.com/wkentaro/pytorch-fcn/blob/e86a0f08bbc6fa4033b1e9d15c8ddb70a9537bb5/examples/voc/train_fcn32s.py#L42
