### ISSUE TITLE
 fcn.utils.visualize_segmentation,where the  visualize_segmentation function?

### ISSUE THREAD

**Issue by liul-ing** [wkentaro/pytorch-fcn#164]
"viz = fcn.utils.visualize_segmentation(lbl_pred=lp, lbl_true=lt, img=img, n_class=n_class)  " in the validate function in trainer.py,i can not find the visulaize_segmentation function.could you please tell me about my questions?

**Comment by wkentaro** [comment]
Please follow the instruction.
https://github.com/wkentaro/pytorch-fcn#installation
