### ISSUE TITLE
speedtest

### ISSUE THREAD

**Issue by sophia723** [wkentaro/pytorch-fcn#21]
Hi,

Thanks for sharing the code. I wonder that what kind of GPU were you using for speed test? When I ran the speed test on GTX 1080 (8G memory), the Elapsed time for chainer is: 404.87 [s / 1000 evals] and the for pytorch, it is 178.93 [s / 1000 evals]. And whenever I try to run it with the VOC dataset, it has the out of memory error, so I wonder if you can share your experiment environment, such as GPU type, how long it runs and how much memory fcn32s_pytorch takes. 

Thank you!

**Comment by wkentaro** [comment]
I'm testing on TitanX Pascal 12GB memory GPU, and the training takes around 2 days with VOC dataset.
