### ISSUE TITLE
strange error unknown

### ISSUE THREAD

**Issue by zheshiyige** [wkentaro/pytorch-fcn#22]
Hi, 
       When I run the examples/voc/train_fcn32s.py.  There is a strange error
       File "train_fcn32s.py", line 46, in main
    model = torchfcn.models.FCN32s(n_class=21, deconv=deconv)
   TypeError: __init__() got an unexpected keyword argument 'deconv'
    could you tell me what's wrong with this error?
Thanks and Best Regards,

**Comment by wkentaro** [comment]
Thank you for the report! I fixed it.
