### ISSUE TITLE
AttributeError: ' module object has no attribute 'utils'

### ISSUE THREAD

**Issue by zheshiyige** [wkentaro/pytorch-fcn#25]
Hi, 
       So sorry to bother you again!
       Now, there is a new error
       Traceback (most recent call last):
  File "voc/train_fcn32s.py", line 100, in <module>
    main()
  File "voc/train_fcn32s.py", line 56, in main
    torchfcn.utils.copy_params_vgg16_to_fcn32s(vgg16, model, init_upscore=False)
AttributeError: 'module' object has no attribute 'utils'

       But I found that I have installed torchfcn (1.4.1) and can import torchfcn.

Thanks and Best Regards,

**Comment by wkentaro** [comment]
Fixed via #26, Please try again.
