### ISSUE TITLE
how to provide the three arguments in train_fcn32s.py

### ISSUE THREAD

**Issue by zheshiyige** [wkentaro/pytorch-fcn#28]
Hi,
         So sorry to bother you again!    Could you tell me what's the meaning of the three arguments, out, resume and no-deconv? How to provide these three arguments to make it run properly?

Thanks and Best Regards,

**Comment by wkentaro** [comment]
You can just run ./train_fcn32s.py --out logs/fcs32s_sbd

**Comment by wkentaro** [comment]
--out is log output destination directory,
--resume is in order to resume the training from checkpoint,
--no-deconv is to use FCN model without deconvolution layer.
