### ISSUE TITLE
Is there implementation of FCN16s and FCN8s

### ISSUE THREAD

**Issue by zheshiyige** [wkentaro/pytorch-fcn#34]
Hi,
       I can only find fcn32s implementation in VOC example, is there fcn16s and fcn8s implementation?

Thanks and Best Regards,

**Comment by wkentaro** [comment]
Currently no.

**Comment by acgtyrant** [comment]
I am amazing there is still no implementation of them now...

**Comment by wkentaro** [comment]
Closed via #49 #47 #48
