### ISSUE TITLE
Incosistent Tensor size while loading data using data loader.

### ISSUE THREAD

**Issue by Deepayan137** [wkentaro/pytorch-fcn#38]
I am training an OCR using RNN. I am supplying input data as word images of varying dimensions (since each word can be of different lengths) and the size of class labels of each input data is also not consistent. Since each word can have a different number of characters.

```python
   tensor_word_dataset = WordImagesDataset(images, truths, transform = ToTensor())
   dataset_loader = torch.utils.data.DataLoader(tensor_word_dataset,
                                            batch_size=16, shuffle=True,) 
```

This gives me the error:
`RuntimeError: inconsistent tensor size at /py/conda-bld/pytorch_1493673470840/work/torch/lib/TH/generic/THTensorCopy.c:46
`

The image sizes of first 5 input labels and images respectively  are:
```
 torch.Size([2]) torch.Size([32, 41])
 torch.Size([7]) torch.Size([32, 95])
 torch.Size([2]) torch.Size([32, 38])
 torch.Size([2]) torch.Size([32, 53])
 torch.Size([2]) torch.Size([32, 49])
 torch.Size([6]) torch.Size([32, 55])
 ```

Any suggestions as to how should I fix it. I want to shuffle the data and send it in batches instead of supplying them one at a time.

**Comment by deartonym** [comment]
I have exactly the same error and am trying to figure out as well.

**Comment by Deepayan137** [comment]
I resolved this issue by padding my images and my labels so that they become of uniform dimension.
I took the image with maximum width and then padded all other images by adding 1 on both left and right side. 
```
class zeroPadding(object):
	def __call__(self, sample):
		image, truth = sample['image'], sample['ground truth']
		image_height = image.shape[0]
		image_width = image.shape[1]
		
		#height_diff = max_height - image_height
		width_diff  = max_width - image_width
		
		left=width_diff//2
		right=width_diff - left
		#print(left, right)
		top = 0
		bottom = 0
		constant = cv2.copyMakeBorder(image,0,0,left,right, cv2.BORDER_CONSTANT, value= 1)
		return {'image': constant,
				'ground truth': truth}
```

for Lables I ttok the longest sequence among all the labels.

```


	
	data =torch.zeros((lsequence))
	lensequence = []
	
	for i, letter in enumerate(sequence):
		try:
			
			data[i] = lettertoindex(letter)
			
			#su = su|data[i,:]
		except:
			print(i,letter)
	
	return (data.int())
```
