### ISSUE TITLE
Could you plz add more running instructions on /example/voc/train_fcn32s.py

### ISSUE THREAD

**Issue by deartonym** [wkentaro/pytorch-fcn#39]
As the title, thanks. It seems that 

`./train_fcn32s.py --out logs/fcs32s_sbd`

does not work out with the current version.

Best,

**Comment by deartonym** [comment]
It works with:
`./train_fcn32s.py ./config/001.yaml`

**Comment by wkentaro** [comment]
Thanks! I fixed the document: https://github.com/wkentaro/pytorch-fcn/commit/6a9e842cd97f28acdce415ecc821f325fadd4604
