### ISSUE TITLE
About the offset of crop

### ISSUE THREAD

**Issue by volzkzg** [wkentaro/pytorch-fcn#50]
Hi, I just want to ask how you decide the crop offset in different models. If I want to train this model on different datasets with different image size, how to calculate the precise crop offset?

**Comment by wkentaro** [comment]
There is enough padding (100) in the first layer (conv1_1), so maybe you don't have to do tune the parameter even though using different datasets.
I have experiences of using FCN with different datasets, but had no problems.

**Comment by volzkzg** [comment]
Thanks, it worked on 2048x1024 images.
