### ISSUE TITLE
Questions about the parameters in the upscore layer

### ISSUE THREAD

**Issue by WeiQijie** [wkentaro/pytorch-fcn#51]
Hi @wkentaro ,your code is running will on my own dataset but there are some parts that I don't quite understand.
In [fcn32s.py](https://github.com/wkentaro/pytorch-fcn/blob/master/torchfcn/models/fcn32s.py) line 144 you set
```h = h[:, :, 19:19 + x.size()[2], 19:19 + x.size()[3]].contiguous()```. 
Why you use 19 here or I can just replace it with 20 or 18?
Thanks very much.

**Comment by wkentaro** [comment]
It is the minimum padding/offset possible as the output of deconvolution.
You can compute it with different input size.

**Comment by wkentaro** [comment]
You can compute the min/max offsets below for FCN32s:
https://gist.github.com/wkentaro/1d32e54535f0486d09e962302a9bc068

It shows the minimum offset is 19.0 and maximum is 34.5.
