### ISSUE TITLE
Can not work with pycaffe?

### ISSUE THREAD

**Issue by chenchr** [wkentaro/pytorch-fcn#53]
Hello! I am using your pytorch-fcn, which need the dependency fcn. However, when I try to convert the caffe model to pytorch one, importing both fcn and caffe the kernel become dead. But just importint single one, caffe or fcn, it works. If I import fcn after importing caffe or caffe after fcn, it can not work...

**Comment by chenchr** [comment]
Hello. I found that the usage of fcn is a classmethod of model to download the pre-trained model. Is the model converted from pre-trained caffe model or trained by pytorch-fcn?

**Comment by wkentaro** [comment]
> Is the model converted from pre-trained caffe model..

fcn downloads model trained using caffe.

**Comment by chenchr** [comment]
@wkentaro Thanks! Maybe I can download the model from browser and comment out the code using fcn.
