### ISSUE TITLE
an issue about train_data

### ISSUE THREAD

**Issue by jacktkk** [wkentaro/pytorch-fcn#58]
hi man~ sorry for bothering u
I can not get the  http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/sema
ntic_contours/benchmark.tgz -O benchmark.tar  for the benchmark data.
Could u please upload the files to your project? 
thx!

**Comment by wkentaro** [comment]
I tried now, and I successfully downloaded that `benchmark.tgz` file.
Could you try again?

**Comment by jacktkk** [comment]
I finished it by using windows system, thanks for your reply : )
