### ISSUE TITLE
BC Support

### ISSUE THREAD

**Issue by FuriouslyCurious** [wkentaro/pytorch-fcn#6]
Hi WKentaro,

Thank you for the implementation!  I am new to PyTorch and I will try this out for an upcoming project.  

Does your implementation include Bottleneck (BC) blocks?  It seems to improve training time significantly. 

- FC

**Comment by FuriouslyCurious** [comment]
My apologies - I mistakenly thought that this repo was DenseNet FCN Tiramisu implementation. 

https://arxiv.org/pdf/1611.09326v1.pdf

**Comment by wkentaro** [comment]
That would be fine of supporting DenseNet FCN as well..
