### ISSUE TITLE
AttributeError: 'float' object has no attribute 'total_seconds'

### ISSUE THREAD

**Issue by quinwu** [wkentaro/pytorch-fcn#61]
Hi,wkentrao. sorry to bother u ! 
I want to train fcn32s , like this.
> ./train_fcn32s.py -g 0

Now,i have a error. I dont know how to fixed that.

> Traceback (most recent call last):
>   File "./train_fcn32s.py", line 164, in <module>
>     main()
>   File "./train_fcn32s.py", line 160, in main
>     trainer.train()
>   File "/home/wukuan/anaconda3/envs/env27/lib/python2.7/site-packages/torchfcn/trainer.py", line 222, in train
>     self.train_epoch()
>   File "/home/wukuan/anaconda3/envs/env27/lib/python2.7/site-packages/torchfcn/trainer.py", line 208, in train_epoch
>     elapsed_time = elapsed_time.total_seconds()
> AttributeError: 'float' object has no attribute 'total_seconds'

I want to know some details about this error.
Thanks and Best Regards!

**Comment by wkentaro** [comment]
I think it is fixed via  9ada6ed could you please check?
