### ISSUE TITLE
ImportError: No module named fcn

### ISSUE THREAD

**Issue by xiaogangw-zz** [wkentaro/pytorch-fcn#62]
Hi, when I run the file "model_caffe_to_pytorch.py", it turns out that there is "no module named fcn". Thank you very much.
By the way, "export PYTHONAPTH=$(pwd)/python:$PYTHONPATH" should be "export PYTHONPATH=$(pwd)/python:$PYTHONPATH", I think.

**Comment by wkentaro** [comment]
Please follow the instruction: https://github.com/wkentaro/pytorch-fcn#installation

I will fix the typo. Thank you.

**Comment by wkentaro** [comment]
The typo is fixed via: 0f325e86b6158503468380127684b6217f508485
