### ISSUE TITLE
Initialize fcn8s by weights of vgg16 by the same way in fcn32s.

### ISSUE THREAD

**Issue by fighterstz** [wkentaro/pytorch-fcn#68]
Hello, thanks for your efforts! 
But I encountered a problem when I initialize fcn8s and fcn16s by weights of vgg16 by the same way in fcn32s. The training results (especially fcn8s) didn't reach the expectation because the mean_iu is very low. Can you tell me where it's possible wrong?
Look forward to your reply.

**Comment by wkentaro** [comment]
It is not possible to train fcn8s with finetuning from vgg16.
To do this, you should use fcn8s_atonce model: https://github.com/wkentaro/pytorch-fcn/blob/master/torchfcn/models/fcn8s.py#L172

(this is described in the original paper)

**Comment by fighterstz** [comment]
Got it! thank you!
