### ISSUE TITLE
question about learning_curve.py

### ISSUE THREAD

**Issue by haomengchao** [wkentaro/pytorch-fcn#70]
Hi, thank you for sharing the code. I trained FCN32s on VOC12 and got the correct results when using view_log. However, when I tried to draw the learning curves, my log  couldn't work with the code.  After 
 **rolling_mean**  , all the data in **df_train** became NaN. Is there something wrong with my log? There are some pics about this problem.
![step4](https://user-images.githubusercontent.com/31341358/41076832-2170871a-6a46-11e8-9bdf-a55f3170838b.png)
![step5](https://user-images.githubusercontent.com/31341358/41076839-295d0e80-6a46-11e8-8147-aa3d6b075adc.png)
Do you know how to fix it? Thank you very much. @wkentaro

**Comment by wkentaro** [comment]
Hmm, I have no idea. 
If you provide me the log.csv, I think I can get to know the cause.

**Comment by haomengchao** [comment]
@wkentaro sorry to disturb you. How can I provide it to you?
Thanks

**Comment by wkentaro** [comment]
I usually use gist for that.
You can also use Dropbox and Google Drive.

**Comment by haomengchao** [comment]
I post it on Google Drive
https://drive.google.com/open?id=13Yv1i7yNnsxl2fjcQHvw5xlkUkgB5IzO 
@wkentaro

**Comment by wkentaro** [comment]
697f8647bb3fcd4f3af27eda0931f350017a7573 should fix this issue.
So please use the latest pytorch-fcn by `git pull origin master`.

**Comment by haomengchao** [comment]
@wkentaro yeah the bug is fixed.
Thank you!

**Comment by wkentaro** [comment]
👍
