### ISSUE TITLE
no module named fcn

### ISSUE THREAD

**Issue by sangeet259** [wkentaro/pytorch-fcn#71]
in fcn8s.py it attempts `import fcn` but there is no such module

**Comment by sangeet259** [comment]
Oh, found the issue already closed. 
Sorry for the inconvenience :)

**Comment by zzllc3** [comment]
@sangeet259 hi, I met the same problem. How did you solve it? thanks

**Comment by wkentaro** [comment]
Please read the README. 
`pip install torchfcn`

**Comment by WeiShi-9** [comment]
you can try pip install fcn, fcn is a package name of python. good luck
