### ISSUE TITLE
Error when run command"pip install torchfcn"

### ISSUE THREAD

**Issue by CLAPoo** [wkentaro/pytorch-fcn#74]
when i run the command:
          pip install torchfcn
i got the error like this.  I have tried re-install torch, but the bug is still here.

**Log:**
Installing collected packages: torchfcn
  Running setup.py install for torchfcn ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-EVS88p/torchfcn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-W87s66/install-record.txt --single-version-externally-managed --compile:
    running install
```
 error: can't copy 'torchfcn/ext/fcn.berkeleyvision.org': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-EVS88p/torchfcn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-W87s66/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-EVS88p/torchfcn/
chao@user-Server:~/chao/action/segmentation/pytorch-fcn$ sudo pip uninstall torchfcn

**Comment by CLAPoo** [comment]
@wkentaro

**Comment by wkentaro** [comment]
Actually, I can't reproduce this.
Could you please provide the information of your environment?

**Comment by CLAPoo** [comment]
Ubuntu 16.04
Requirement already satisfied: fcn>=6.1.5 in /usr/local/lib/python2.7/dist-packages (from torchfcn) (6.4.5)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from torchfcn) (1.14.5)
Requirement already satisfied: Pillow in /usr/local/lib/python2.7/dist-packages (from torchfcn) (4.3.0)
Requirement already satisfied: scipy in /usr/lib/python2.7/dist-packages (from torchfcn) (0.17.0)
Requirement already satisfied: torch>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from torchfcn) (0.4.0)
Requirement already satisfied: torchvision>=0.1.8 in /usr/local/lib/python2.7/dist-packages (from torchfcn) (0.2.0)
Requirement already satisfied: tqdm in /usr/local/lib/python2.7/dist-packages (from torchfcn) (4.23.4)
Requirement already satisfied: chainer>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from fcn>=6.1.5->torchfcn) (4.2.0)
Requirement already satisfied: chainercv in /usr/local/lib/python2.7/dist-packages (from fcn>=6.1.5->torchfcn) (0.10.0)
Requirement already satisfied: gdown in /usr/local/lib/python2.7/dist-packages (from fcn>=6.1.5->torchfcn) (3.5.0)
Requirement already satisfied: matplotlib in /usr/lib/python2.7/dist-packages (from fcn>=6.1.5->torchfcn) (1.5.1)
Requirement already satisfied: pandas in /usr/local/lib/python2.7/dist-packages (from fcn>=6.1.5->torchfcn) (0.22.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python2.7/dist-packages (from fcn>=6.1.5->torchfcn) (3.12)
Requirement already satisfied: scikit-learn in /usr/lib/python2.7/dist-packages (from fcn>=6.1.5->torchfcn) (0.17)
Requirement already satisfied: scikit-image in /usr/lib/python2.7/dist-packages (from fcn>=6.1.5->torchfcn) (0.10.1)
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow->torchfcn) (0.44)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from torchvision>=0.1.8->torchfcn) (1.11.0)
Requirement already satisfied: filelock in /usr/local/lib/python2.7/dist-packages (from chainer>=2.0.0->fcn>=6.1.5->torchfcn) (3.0.4)
Requirement already satisfied: protobuf>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from chainer>=2.0.0->fcn>=6.1.5->torchfcn) (3.5.0.post1)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from gdown->fcn>=6.1.5->torchfcn) (2.18.4)
Requirement already satisfied: pytz>=2011k in /usr/lib/python2.7/dist-packages (from pandas->fcn>=6.1.5->torchfcn) (2014.10)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/dist-packages (from pandas->fcn>=6.1.5->torchfcn) (2.4.2)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf>=3.0.0->chainer>=2.0.0->fcn>=6.1.5->torchfcn) (20.7.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->gdown->fcn>=6.1.5->torchfcn) (1.22)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->gdown->fcn>=6.1.5->torchfcn) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->gdown->fcn>=6.1.5->torchfcn) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->gdown->fcn>=6.1.5->torchfcn) (2018.4.16)

@wkentaro

**Comment by wkentaro** [comment]
I also use Ubuntu 16.04, but can't reproduce this. I'm not sure how to fix your problem.

**Comment by wkentaro** [comment]
Probably, your pip is old.
What about upgrading it by `pip install -U pip`?

**Comment by pamela0530** [comment]
i meet the same problem

**Comment by Jee-King** [comment]
i meet the same problem when using `'sudo pip3 install .'`
but it works when using `'sudo pip install .'`
so could you give me some suggestions?
thank you.
