### ISSUE TITLE
Is there any pre-trained model released?

### ISSUE THREAD

**Issue by yifanjiang19** [wkentaro/pytorch-fcn#79]
Will you release any pre-trained model? That will be very helpful.

**Comment by wkentaro** [comment]
See https://github.com/wkentaro/pytorch-fcn/blob/63bc2c5bf02633f08d0847bb2dbd0b2f90034837/torchfcn/models/fcn32s.py#L31-L37.

**Comment by MohitTare** [comment]
Thanks for sharing this awesome repo. I am trying to use the pre-trained FCN8 model by directly loading the state dictionary, however i am not seeing any output (segmentation map). Below is the snapshot of my code


```
state_dct = torch.load("C:\\Users\\mohit/data/models/pytorch/fcn8s_from_caffe.pth")
model = torchfcn.models.FCN8s()

model.load_state_dict(state_dct)

op = model(images)
seg_map = op.max(1)[1].cpu().numpy()
plt.imshow(segmap)
```

I am doing it correctly. My understanding is that the op is for each classes (one hot) and we need to take the max accross each channel. Can you please assist in resolving?
