### ISSUE TITLE
How to find the slicing index at last layer ?

### ISSUE THREAD

**Issue by AtsukiOsanai** [wkentaro/pytorch-fcn#82]
Hi,

I'm studying semantic segmentation and have a question about fcn.

At fcn32s, you are slicing the upscore from "19".
Also, at fcn16s, you are using the index "5" after score_pool4 and "27" after upscore16. 
How did you find this index ?
(I think it causes because of padding(=100) at first layer.)

Specifically, if my calculation is correct, (3, 224, 224) input gives (n_class, 288, 288) output for fcn32s.
So, we have many choices to crop the same size with the input.
How did you choose current indices ? 

Thanks,

**Comment by wkentaro** [comment]
You can check this issue: https://github.com/wkentaro/fcn/issues/102.

And below is the simple code to get the crop size for FCN32s:
https://gist.github.com/wkentaro/1d32e54535f0486d09e962302a9bc068#file-get_fcn32s_offsets-py
