### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by kcyu2014** [wkentaro/pytorch-fcn#85]
Hi,

I want to test on the example cases, so I just run `python example/voc/train_fcn8s.py -g 1` on a DGX station, with Tesla V100 16GB memory. After loading the model, it immediately reports out of memory in the first forward pass. Has anyone encountered this situation?

environment:
Pytorch: v0.4.1
CUDA: 9.0
cuDNN: 7.1.4

Kaicheng

**Comment by mqp2259** [comment]
I have the same problem. Did you solve it?

**Comment by wkentaro** [comment]
Probably, it's the problem of pytorch you use.
Have you tested with a simpler training code? Like train_mnist.py?

**Comment by zl535320706** [comment]
> Probably, it's the problem of pytorch you use.
> Have you tested with a simpler training code? Like train_mnist.py?

I have the same problem with k40 11G memory, and I find the bath_size=1 in train_fcn8s.py. Why the code need so much memory? I had run others segementation code in VOC 2012, and do not find the same problem. What shold I do to run this code?  I'm sure that my pytorch(stable 0.4.1 cuda80) works well. 

I find that while running to the fcn8s.py"127:     h = self.relu6(self.fc6(h))", the GPU would be out of memory, and "self.fc6 = nn.Conv2d(512, 4096, 7)" in def  __init__, which is same as [https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc-fcn8s/train.prototxt](url) 

> layer {
  name: "fc6"
  type: "Convolution"
  bottom: "pool5"
  top: "fc6"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 4096
    pad: 0
    kernel_size: 7
    stride: 1
  }
> 
So, I have no idea....

OK, I seem to solved this problem. Just modify the input image to 224*224, like original paper FCN. The output of self.fc6 should be 1*4096*1*1, and there will not be out of momory.

**Comment by wkentaro** [comment]
Hmm, I tested this on Titan X, Titan X Pascal, and GTX 1080Ti, which have 12 or 11 G memories..

**Comment by peytonhong** [comment]
@wkentaro Have you ever tried it with Pytorch 0.4.1 the latest version? I am also using Titan X but get the message "CUDA error: out of the memory" whenever I run the code "python train_fcn32s.py -g 0". I already checked the mnist example which is working properly with gpu.

**Comment by wkentaro** [comment]
Maybe no. I haven't tested on the newer PyTorch.

**Comment by gyheart** [comment]
> @wkentaro Have you ever tried it with Pytorch 0.4.1 the latest version? I am also using Titan X but get the message "CUDA error: out of the memory" whenever I run the code "python train_fcn32s.py -g 0". I already checked the mnist example which is working properly with gpu.

Have you solved the problem？ I also  have the same problem

**Comment by peytonhong** [comment]
@gyheart This code was worked at Pytorch 0.3 version. Thanks!

**Comment by gyheart** [comment]
> @gyheart This code was worked at Pytorch 0.3 version. Thanks!

Is the version 0.3.1？Thanks！
