### ISSUE TITLE
run on multi-gpu

### ISSUE THREAD

**Issue by qiaokang0** [wkentaro/pytorch-fcn#86]
python train_fcn16s.py -g 0
i change:
1. os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3'
2. model=model.cuda() -> model=torch.nn.DataParallel(model,device_ids=[2,3])
for i want use the last gpus for training.

and i get error below ,i only know the para_copy op causes this,
 i am a newbee for pytorch, any sulotion or pointer accroding which i can try?

Traceback (most recent call last):
  File "train_fcn16s.py", line 120, in <module>
    main()
  File "train_fcn16s.py", line 100, in main
    weight_decay=cfg['weight_decay'])
  File "/home/qk/anaconda3/lib/python3.6/site-packages/torch/optim/sgd.py", line 64, in __init__
    super(SGD, self).__init__(params, defaults)
  File "/home/qk/anaconda3/lib/python3.6/site-packages/torch/optim/optimizer.py", line 43, in __init__
    self.add_param_group(param_group)
  File "/home/qk/anaconda3/lib/python3.6/site-packages/torch/optim/optimizer.py", line 186, in add_param_group
    param_group['params'] = list(params)
  File "/home/qk/pytorch-fcn/examples/voc/train_fcn32s.py", line 82, in get_parameters
    raise ValueError('Unexpected module: %s' % str(m))
ValueError: Unexpected module: DataParallel(
  (module): FCN16s(
    (conv1_1): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(100, 100))
    (relu1_1): ReLU(inplace)
    (conv1_2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu1_2): ReLU(inplace)
    (pool1): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=True)
    (conv2_1): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu2_1): ReLU(inplace)
    (conv2_2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu2_2): ReLU(inplace)
    (pool2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=True)
    (conv3_1): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu3_1): ReLU(inplace)
    (conv3_2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu3_2): ReLU(inplace)
    (conv3_3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu3_3): ReLU(inplace)
    (pool3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=True)
    (conv4_1): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu4_1): ReLU(inplace)
    (conv4_2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu4_2): ReLU(inplace)
    (conv4_3): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu4_3): ReLU(inplace)
    (pool4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=True)
    (conv5_1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu5_1): ReLU(inplace)
    (conv5_2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu5_2): ReLU(inplace)
    (conv5_3): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (relu5_3): ReLU(inplace)
    (pool5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=True)
    (fc6): Conv2d(512, 4096, kernel_size=(7, 7), stride=(1, 1))
    (relu6): ReLU(inplace)
    (drop6): Dropout2d(p=0.5)
    (fc7): Conv2d(4096, 4096, kernel_size=(1, 1), stride=(1, 1))
    (relu7): ReLU(inplace)
    (drop7): Dropout2d(p=0.5)
    (score_fr): Conv2d(4096, 21, kernel_size=(1, 1), stride=(1, 1))
    (score_pool4): Conv2d(512, 21, kernel_size=(1, 1), stride=(1, 1))
    (upscore2): ConvTranspose2d(21, 21, kernel_size=(4, 4), stride=(2, 2), bias=False)
    (upscore16): ConvTranspose2d(21, 21, kernel_size=(32, 32), stride=(16, 16), bias=False)
  )
)

**Comment by wkentaro** [comment]
Actually, pytorch-fcn does not work with multi-gpu. I think we need to change some of the code to run with multi-gpu.
