### ISSUE TITLE
what is FWAV stand for in metric?

### ISSUE THREAD

**Issue by hubutui** [wkentaro/pytorch-fcn#92]
The [paper](https://www.cv-foundation.org/openaccess/content_cvpr_2015/html/Long_Fully_Convolutional_Networks_2015_CVPR_paper.html) use "pixel accuracy, mean accuraccy, mean IU, frequency weighted IU". And the evaluate script report "Accuracy, Accuracy Class, Mean IU, FWAV Accuracy". I'm a little confused.

pixel accuracy <-> Accuracy
mean accuracy <-> Accuracy Class
mean IU <-> Mean IU
frequency weighted IU <-> FWAW Accuracy

Is that right?

**Comment by wkentaro** [comment]
Ya. FWAV Accuracy represents Frequency Weighted AVraged Accuracy
