### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by BenfenYU** [wkentaro/pytorch-fcn#96]
Hi, may I ask you a question?
How does your test_fcn32s work?
I can't find any trained model like *.pth used in your code.
Thank you so much!

**Comment by wkentaro** [comment]
It downloads from Google Drive: https://github.com/wkentaro/pytorch-fcn/blob/f6766058ad7968721f6217c378dff32716ee9fc6/torchfcn/models/fcn32s.py#L31-L37

**Comment by BenfenYU** [comment]
well , that is not what I mean .
emmmmm , ask you later.
Thank you

**Comment by wkentaro** [comment]
Ah I see. Actually, the test does not use the pretrained model at the moment.
